language: objective-c
osx_image: xcode9
xcode_project: YCDownloadSessionDemo.xcworkspace
xcode_scheme: YCDownloadSessionDemo

before_install:
- env
- xcodebuild -version
- xcodebuild -showsdks
- xcpretty --version

script:
- set -o pipefail
- xcodebuild clean build -workspace "$TRAVIS_XCODE_PROJECT"  -scheme "$TRAVIS_XCODE_SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' | xcpretty
